### ISSUE TITLE
no docs for orange pi zero 2

### ISSUE THREAD

**Issue by alexgubanow** [orangepi-xunlong/opi-documentation#1]
hi, please share docs on new board "orange pi zero 2"
i have got mine from here: https://www.aliexpress.com/item/1005001823662622.html

**Comment by orangepi-xunlong** [comment]
http://www.orangepi.org/downloadresources/

![图片](https://user-images.githubusercontent.com/10287101/138231812-dcffb313-8c4a-4732-a7a3-7380c12ab19a.png)

**Comment by alexgubanow** [comment]
By this link i can'ty find mechanical drawings, i need to design expansion board and case for "orange pi zero 2"
where can i find it?
